<a href="https://colab.research.google.com/github/Jasonkodet005/She-code/blob/main/CIR203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
total=np.array([
    [10000,12000,7000,30000,54000,20000],
    [3200,45000,31000,6700,17000,6500],
    [3700,4100,9800,6700,3900,8700],
    [5600,7800,9800,7600,2100,3200]
])
print(total)

total_per_branch=total.sum(axis=1)
print(total_per_branch)

highest_branch=np.argmax(total_per_branch)+1
print("branch with the highest total transaction",highest_branch)

average_monthly=transaction.mean()
print("average monthly transaction",average_monthly)

reshape=transaction.reshape(3,8)
print(reshape)

[[10000 12000  7000 30000 54000 20000]
 [ 3200 45000 31000  6700 17000  6500]
 [ 3700  4100  9800  6700  3900  8700]
 [ 5600  7800  9800  7600  2100  3200]]
[133000 109400  36900  36100]
branch with the highest total transaction 1
average monthly transaction 13141.666666666666
[[10000 12000  7000 30000 54000 20000  3200 45000]
 [31000  6700 17000  6500  3700  4100  9800  6700]
 [ 3900  8700  5600  7800  9800  7600  2100  3200]]
